import Link from "next/link";
import { PROFILE } from "@/lib/data";

export const metadata = {
  title: "Privacy Policy | Goran",
  description: "Privacy policy for Goran's portfolio website.",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen">
      <div className="mx-auto max-w-3xl px-4 py-12">
        <Link
          href="/"
          className="text-sm underline underline-offset-4 opacity-80 hover:opacity-100"
        >
          ← Back to home
        </Link>

        <h1 className="mt-6 text-3xl font-semibold tracking-tight">Privacy Policy</h1>
        <p className="mt-4 text-sm leading-relaxed opacity-85">
          This site is a personal portfolio. It does not sell, rent, or share personal data.
        </p>

        <h2 className="mt-8 text-lg font-semibold">What data is collected</h2>
        <ul className="mt-3 list-disc space-y-2 pl-5 text-sm opacity-85">
          <li>
            If you contact me (for example via email or a contact form), I will receive the information you
            send (such as your email address and message).
          </li>
          <li>
            Basic, aggregated technical logs (for example, standard hosting logs) may be generated by the
            hosting provider to operate the website.
          </li>
        </ul>

        <h2 className="mt-8 text-lg font-semibold">How data is used</h2>
        <ul className="mt-3 list-disc space-y-2 pl-5 text-sm opacity-85">
          <li>To respond to your inquiry and communicate with you.</li>
          <li>To maintain the security and reliability of the site.</li>
        </ul>

        <h2 className="mt-8 text-lg font-semibold">Contact</h2>
        <p className="mt-3 text-sm opacity-85">
          If you have questions about this policy, contact: {" "}
          <Link className="underline underline-offset-4" href={`mailto:${PROFILE.email}`}>
            {PROFILE.email}
          </Link>
        </p>
      </div>
    </main>
  );
}
